default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chitterapp_development

test:
  <<: *default
  database: chitterapp_test

production:
  <<: *default
  database: chitterapp_production
  username: chitterapp
  password: <%= ENV['CHITTERAPP_DATABASE_PASSWORD'] %>
